version: '3.2'

services:
  bus_tickets:
    image: grokkertech/bus_tickets
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
    driver: local
